# Generated by Django 3.2.10 on 2023-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ip_addresses',
            field=models.TextField(blank=True),
        ),
    ]
