# Generated by Django 3.2.10 on 2023-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20230520_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_login_verified',
            field=models.BooleanField(default=False),
        ),
    ]
