# Generated by Django 3.2.10 on 2023-05-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_userprofile_is_login_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_login_verified',
        ),
    ]
