# Generated by Django 3.2.10 on 2023-05-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
