# Generated by Django 3.2.10 on 2023-05-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='zemlja.jpg', upload_to='post_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komentar',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentari', to='MyApp.post'),
        ),
    ]
