# Generated by Django 3.2.10 on 2023-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
